sidebar_userinfo_background_default:
  type: string
  default: 'https://vaperina-assets-02-cdn.b-cdn.net/assets/left-menu/left-panel-background1.jpg'
  description:
    en: 'Default background of the userInfo field in the sidebar.'
sidebar_extra_links:
  type: list
  default: 'VapeDIY,https://diy.vaperina.cc,flask|Vaper Lokátor,/u/user-map?period=location,compass|Támogatás,/t/tamogato-leszek/601,heartbeat|Aukció,/c/tamogatas/aukcio/51,gavel|Vaperina Live,/c/vaperina-live/57,users|Útmutató az oldalhoz,/t/utmutato-az-oldal-hasznalatahoz/757,question-circle|Bizalmi szintek,/t/kozossegepites-felsofokon-bizalmi-szintek-korlatozasok/718,certificate'
  description:
    en: 'Additional links. Format: <name>,<url>[,<icon>]'
